name: PS
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.8.10
  - pip==21.1.2
  - pytorch==1.9.0
  - pip:
    - matplotlib==3.4.2
    - GitPython==3.1.18
    - jupyter==1.0.0
    - numpy==1.20.3
    - scipy==1.6.3
    - scikit-learn==0.24.2
    - tensorboard==2.5.0
    - networkx==2.5.1
    - python-igraph==0.9.6
    - pycairo==1.20.1
    - ipykernel==5.5.5
