name: PS
channels:
  - pytorch
  - conda-forge
  - rusty1s
  - defaults
dependencies:
  - python=3.8.10
  - pip==21.1.2
  - ipykernel
  - cudatoolkit
  - torchaudio
  - torchvision
  - pytorch
  - pytorch-geometric
  
  - pip:
    - matplotlib
    - GitPython
    - jupyter
    - numpy
    - scipy
    - scikit-learn
    - tensorboard
    - networkx
    - python-igraph
    - pycairo
    - ogb
