name: PS
channels:
  - pytorch
  - conda-forge
  - rusty1s
  - defaults
dependencies:
  - python=3.8.11
  - pip==21.1.2
  - ipykernel
  - cudatoolkit=11.1
  - torchaudio
  - torchvision
  - pytorch
  - pytorch-geometric=1.7.2
  
  - pip:
    - matplotlib
    - GitPython
    - jupyter
    - numpy
    - scipy
    - scikit-learn
    - tensorboard
    - networkx
    - ogb
